name: Run Newman Tests

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: |
        npm install -g newman
        npm install -g newman-reporter-html  # Install any reporters you need

    - name: Run Newman
      run: |
        newman run path/to/your/collection.json -e path/to/your/environment.json -r html
